# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:12.5
    container_name: zoom-bot-postgres-db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: zoomer
    ports:
      - 5432:5432